services:
  - type: web # немесе worker
    name: chatbot
    runtime: python
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr
      pip install -r requirements.txt
    startCommand: python bot.py
